import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { parseCookies } from "nookies";
import Layout from "src/admin/layout"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BiblioKeia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="http://localhost:8000/docs">BiblioKeia!</a>
        </h1>

      
      </main>

     
    </div>
  )
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};

export const getServerSideProps = async (ctx) => {
  const { ["bibliokeia.token"]: token } = parseCookies(ctx);
  if (!token) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
};
